### ISSUE TITLE
Will cause forum type requests not to jump

### ISSUE THREAD

**Issue by JackeyLov5** [tarampampam/random-user-agent#635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, I've had this problem on one of my forums and it's caused me to make multiple purchases, I haven't noticed this on other sites but I think it's problematic because I'm a Mac user and when I copy it always fails to copy on certain sites. Here's a video that's split into two videos because there's so much information involved.The first video is when I'm commenting and he doesn't refresh the page automatically but it's actually there or the js is asynchronous but when I disable the plugin that doesn't happen.
https://github.com/user-attachments/assets/a4f02b01-aa74-482e-8deb-1a2e95e5337b

### Browser

Chrome

### Extension version

4.3.0

**Comment by tarampampam** [comment]
Could you attach the console logs? Maybe they contain something useful?

And a site URL where this happens?

**Comment by JackeyLov5** [comment]
```
111222
content.js:2 [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.
window.onload @ content.js:2了解此错误AI
content.js:2 [Deprecation] Listener added for a 'DOMCharacterDataModified' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.
window.onload @ content.js:2了解此错误AI
content_script.js:2 this.syncStorageService SyncStorageService
bbs.kafan.cn/:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received了解此错误AI
QHkmCThP.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'dexzhrrv')
    at QHkmCThP.js:10:92
    at QHkmCThP.js:10:5126
（匿名） @ QHkmCThP.js:10
（匿名） @ QHkmCThP.js:10了解此错误AI
evalCore.min.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at evalCore.min.js:1:2708621
    at Gve (evalCore.min.js:1:2708838)
    at Vve (evalCore.min.js:1:2708434)
（匿名） @ evalCore.min.js:1
Gve @ evalCore.min.js:1
Vve @ evalCore.min.js:1了解此错误AI
content.js:2 [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.
window.onload @ content.js:2
load
（匿名） @ content.js:2了解此错误AI
content.js:2 [Deprecation] Listener added for a 'DOMCharacterDataModified' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.
window.onload @ content.js:2
load
（匿名） @ content.js:2了解此错误AI
ajax.js?b33:1 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at HTMLIFrameElement.handleResult (ajax.js?b33:1:1629)
``` 

t00ls.com Comment area
bbs.kafan.cn You can retrieve your password here and test it at will. If you don’t open the plug-in, there will be a prompt message.

**Comment by JackeyLov5** [comment]
> Could you attach the console logs? Maybe they contain something useful?
> 
> And a site URL where this happens?

Hello, I have provided relevant information thk
